### PR TITLE
Add new light icon

### PR DESCRIPTION
**Pull request by JumpLink**
Preview:
light-preview

Example:
Bildschirmfoto vom 2023-05-04 09-44-59

(The example can also be [visited online](https://jumplink.github.io/), but is currently still in progress.)

### CODE REVIEW

**Comment by JumpLink** [comment]
@halfmage Is there any chance that the new icons will be merged?

**Comment by halfmage** [comment]
@JumpLink **thank you very much for your work**.
Let me check the icons in detail and I will come back to you in the next couple of days.

**Comment by halfmage** [comment]
I updated the path, cleaned up the paths and added a filled version.
What do you think? :)

image

**Comment by JumpLink** [comment]
@halfmage Even though each pixel in the icons is strictly 4 pixels in size, I think all pixels should still be the same size. However, your variant on the top right has a thickness of only one pixel for the screw thread. Therefore I would prefer top left and bottom right

**Comment by JumpLink** [comment]
Here are a few more possible variations:

grafik

I would prefer the third last, I find filled variants difficult

**Comment by JumpLink** [comment]
The one who wants to have a luminous lame could then use for example the following variants and color them accordingly:

grafik


Or just this:

grafik

(I have not implemented these examples as vectors now, so that it goes faster)

**Comment by halfmage** [comment]
@JumpLink  maybe it's better to go more minimal here. Did some research and I think these lightbulb variants would fit very well in the set:

image

Let me know what you think.

**Comment by JumpLink** [comment]
@halfmage yea! I like them!
I would be happy if you also add this variant, but would also agree if this is too much for you:

grafik

**Comment by halfmage** [comment]
Added new lightbulb icons in the v1.8 update branch:
https://github.com/halfmage/pixelarticons/compare/v1.8

**Pull request merged**
